export const USER_STATE_CHANGE = 'USER_STATE_CHANGE'
export const USER_POSTS_STATE_CHANGE = 'USER_POSTS_STATE_CHANGE'
export const USER_FOLLOWING_STATE_CHANGE = 'USER_FOLLOWING_STATE_CHANGE'

export const USERS_POSTS_STATE_CHANGE = 'USERS_POSTS_STATE_CHANGE'
export const USERS_LIKES_STATE_CHANGE = 'USERS_LIKES_STATE_CHANGE'
export const USERS_DATA_STATE_CHANGE = 'USERS_DATA_STATE_CHANGE'

export const CLEAR_DATA = 'CLEAR_DATA'
export const SET_USER = 'SET_USER';

export const LOADING_USER = 'LOADING_USER';

export const SET_ERRORS = 'SET_ERRORS';

export const LOADING_UI = 'LOADING_UI';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';

export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';